.TH KTORRENT 1 "JUNE 2007"
.SH NAME
kupnptest \- KTorrent's UPnP test application.
.SH SYNOPSIS
\fBktupnptest\fP [Qt-options] [KDE-options]
.SH DESCRIPTION
.P
\fBKTUPnPTest\fP is a small GUI based helper utility which can be used to
find UPnP capable router(s) on the local network and request them to forward
or unforward (open or close) specific ports to the host running this
application. It's primarily intended to be used to test \fBKTorrent\fP UPnP
plugin settings, but you might find it useful to quickly forward a port to
your host for any other purpose.
.P
\fBKTUPnPTest\fP does not accept any application specific command line options,
but you can use any generic option(s) which are common for all KDE applications.
.SS Generic options
.TP
\fB\-\-help\fP
Show help about options
.TP
\fB\-\-help-qt\fP
Show Qt specific options
.TP
\fB\-\-help-kde\fP
Show KDE specific options
.TP
\fB\-\-help-all\fP
Show all options
.TP
\fB\-\-author\fP
Show author information
.TP
\fB\-v, \-\-version\fP
Show version information
.TP
\fB\-\-license\fP
Show license information
.TP
\fB\-\-\fP
End of options
